---
version: "2.1"
services:
  # https://docs.linuxserver.io/images/docker-code-server
  code-server-service:
    image: lscr.io/linuxserver/code-server
    container_name: code-server-conatiner
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD=password
      - SUDO_PASSWORD=password
      - DEFAULT_WORKSPACE=/config/workspace
      - DOCKER_MODS=xiaohaihuang/code-server-nvm-mod|linuxserver/mods:code-server-extension-arguments
      - VSCODE_EXTENSION_IDS="${VSCODE_EXTENSION_IDS}"
    volumes:
      - /config:/config
    ports:
      - 8443:8443
      - 3000:3000
      - 4000:4000
    restart: unless-stopped
